services:
  compscibot:
    container_name: compscibot
    image: compscibot
    volumes:
      - compscibot-data:/run/data
    environment:
      - DB_PATH=/run/data/bot.db
    env_file: .env
    restart: always

volumes:
  compscibot-data:
